apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieapp
  labels:
    app: movieapp
spec:
  replicas: 1
  selector:
    matchLabels:
      service: movieapp
  template:
    metadata:
      labels:
        app: movieapp
        service: movieapp
    spec:
      containers:
        - name: movieapp
          image: exploredocker.azurecr.io/webapi:v1
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: movieapp
  labels:
    app: movieapp
    service: movieapp
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: movieapp